webtalk_init -webtalk_dir D:/OneDrive - As You Wish/HRX/Programming/Vivado/PipelineCPU/PipelineCPU.sim/sim_1/behav/xsim/xsim.dir/Basys3_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan 24 16:18:02 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "51b512c3-3451-4a94-9383-4725a019f8f0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7849e2be600f4c729b62f4199b70ac49" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "227" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "32.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "27" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "178 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "12 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "149" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "29" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.78_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "63184_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1380774109 -regid "" -xml D:/OneDrive - As You Wish/HRX/Programming/Vivado/PipelineCPU/PipelineCPU.sim/sim_1/behav/xsim/xsim.dir/Basys3_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/OneDrive - As You Wish/HRX/Programming/Vivado/PipelineCPU/PipelineCPU.sim/sim_1/behav/xsim/xsim.dir/Basys3_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/OneDrive - As You Wish/HRX/Programming/Vivado/PipelineCPU/PipelineCPU.sim/sim_1/behav/xsim/xsim.dir/Basys3_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
